echo '==============================='
echo 'Running unit Tests CONTROLLER...'
echo '==============================='
docker exec -it valu_arte python3 -W ignore -m unittest discover -s tests/unit/controller -p 'test_*.py'
echo '==============================='
echo 'Running unit Tests SERVICE...'
echo '==============================='
docker exec -it valu_arte python3 -W ignore -m unittest discover -s tests/unit/service -p 'test_*.py'
